In [4]:
import pandas as pd
import numpy as np
import matplotlib as mp

In [49]:
CALIFORNIA = pd.read_csv('CALIFORNIA.csv', encoding='utf-8')
CAROLINAS = pd.read_csv('CAROLINAS.csv', encoding='utf-8')
CENTRAL = pd.read_csv('CENTRAL.csv', encoding='utf-8')
FLORIDA = pd.read_csv('FLORIDA.csv', encoding='utf-8')
MID_ATLANTIC = pd.read_csv('MID_ATLANTIC.csv', encoding='utf-8')
MIDWEST = pd.read_csv('MIDWEST.csv', encoding='utf-8')
NEW_ENGLAND = pd.read_csv('NEW_ENGLAND.csv', encoding='utf-8')
NEW_YORK = pd.read_csv('NEW_YORK.csv', encoding='utf-8')
NORTHWEST = pd.read_csv('NORTHWEST.csv', encoding='utf-8')
ROCKY_MOUNTAINS = pd.read_csv('ROCKY_MOUNTAINS.csv', encoding='utf-8')
SOUTHEAST = pd.read_csv('SOUTHEAST.csv', encoding='utf-8')
SOUTHWEST = pd.read_csv('SOUTHWEST.csv', encoding='utf-8')
TENNESSEE = pd.read_csv('TENNESSEE.csv', encoding='utf-8')
TEXAS = pd.read_csv('TEXAS.csv', encoding='utf-8')
LABOR = pd.read_csv('laucnty20.csv', encoding='utf-8')

In [26]:
regions = [CALIFORNIA, CAROLINAS, CENTRAL, FLORIDA, MID_ATLANTIC, MIDWEST, NEW_ENGLAND, NEW_YORK, NORTHWEST, ROCKY_MOUNTAINS, SOUTHEAST, SOUTHWEST, TENNESSEE, TEXAS]
USA = pd.DataFrame()
USA = USA.append(regions)

In [61]:
#LABOR.columns
#LABOR = pd.concat([LABOR, LABOR["County Name/State Abbreviation"].str.split(', ', expand=True)], axis=1)
#LABOR.drop([0, 1], axis=1)
#LABOR.rename(columns={0: "County", 1: "State"}, inplace=True)
#LABOR = LABOR.drop(["LAUS Code", "State FIPS Code", "County Name/State Abbreviation", "State"], axis=1)
LABOR

,County FIPS Code,Year,Labor Force,Employed,Unemployed,Unemployment Rate (%),County
0,1,2020,"25,838","24,576","1,262",4.9,Autauga County
1,3,2020,"96,763","91,338","5,425",5.6,Baldwin County
2,5,2020,"8,587","7,982",605,7,Barbour County
3,7,2020,"8,640","8,067",573,6.6,Bibb County
4,9,2020,"24,661","23,653","1,008",4.1,Blount County
...,...,...,...,...,...,...,...
3214,145,2020,N.A.,N.A.,N.A.,N.A.,Vega Baja Municipio
3215,147,2020,N.A.,N.A.,N.A.,N.A.,Vieques Municipio
3216,149,2020,N.A.,N.A.,N.A.,N.A.,Villalba Municipio
3217,151,2020,N.A.,N.A.,N.A.,N.A.,Yabucoa Municipio
3218,153,2020,N.A.,N.A.,N.A.,N.A.,Yauco Municipio

In [62]:
## pd.set_option("display.max_rows", None, "display.max_columns", None)
##USA =  USA[(USA["Aggregation level"] == "County") & (USA["Unit of measure"] == "emissions (tons)") & (USA["Pollutant"] == "CO2")] 
USA =  USA[(USA["Aggregation level"] == "County") & (USA["Unit of measure"] == "percent") & (USA["Pollutant"] == "CO2")] 
USA["Annual Emissions"] = USA["January"] + USA["February"] + USA["March"] + USA["April"] + USA["May"] + USA["June"] + USA["July"] + USA["August"] + USA["September"] + USA["October"] + USA["November"] + USA["December"]
USA = USA.sort_values(by="Annual Emissions", ascending=True)
USA

,Pollutant,Aggregation level,State,County,Unit of measure,January,February,March,April,May,June,July,August,September,October,November,December,Annual Emissions
140,CO2,County,CT,New London County,percent,-1.144786,-0.751129,-1.034826,-1.161545,-0.640775,-1.698697,-0.940723,-0.991301,-1.383137,-1.635844,-1.004683,-0.790304,-13.177751
224,CO2,County,SD,Pennington County,percent,-0.746810,-0.895256,-0.721727,-1.022580,-1.682955,-1.280363,-1.534563,-1.227595,-1.320520,-0.995043,-0.452272,-0.711918,-12.591600
308,CO2,County,ME,Oxford County,percent,-0.860926,-0.447123,-0.688377,-0.949800,-1.407774,-1.347255,-0.840729,-1.073501,-1.062989,-0.916608,-0.367454,-0.488913,-10.451450
200,CO2,County,NY,Lewis County,percent,0.425832,0.918166,-0.252293,-2.176482,-6.754042,-0.637812,-0.489731,-0.263557,1.021866,-4.331307,1.346825,0.921234,-10.271302
164,CO2,County,MA,Barnstable County,percent,-0.466087,-0.700020,-0.329551,-1.520213,-0.254739,-2.284862,-0.976594,-1.072695,-0.876735,-0.287389,-0.765026,-0.525551,-10.059463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,CO2,County,TN,Loudon County,percent,-0.001388,0.021554,0.009133,0.012185,0.012150,0.006859,-0.005413,-0.002997,-0.010571,0.009621,0.013740,0.001715,0.066589
368,CO2,County,KS,Neosho County,percent,0.055406,0.052511,0.049918,0.052868,0.136365,0.009818,-0.045797,-0.042898,-0.000288,0.063197,0.033939,0.048275,0.413314
224,CO2,County,AL,Walker County,percent,-0.067230,-0.346970,-0.021633,0.062201,-0.036093,0.170595,0.182683,0.099168,0.120693,0.070319,0.151112,0.089795,0.474640
1028,CO2,County,TX,Morris County,percent,0.003760,0.025918,0.130578,0.173821,0.017028,0.059573,0.051218,-0.053974,0.044669,0.100263,0.073093,0.050430,0.676378
332,CO2,County,GA,Floyd County,percent,-0.027855,-0.035163,0.235513,0.011975,0.109384,0.125267,0.154349,0.030355,0.094135,0.286799,0.060641,0.151433,1.196833

In [63]:
TOTAL = pd.merge(USA, LABOR, on='County', how='outer')
TOTAL

,Pollutant,Aggregation level,State,County,Unit of measure,January,February,March,April,May,...,October,November,December,Annual Emissions,County FIPS Code,Year,Labor Force,Employed,Unemployed,Unemployment Rate (%)
0,CO2,County,CT,New London County,percent,-1.144786,-0.751129,-1.034826,-1.161545,-0.640775,...,-1.635844,-1.004683,-0.790304,-13.177751,11.0,2020.0,"131,992","119,313","12,679",9.6
1,CO2,County,SD,Pennington County,percent,-0.746810,-0.895256,-0.721727,-1.022580,-1.682955,...,-0.995043,-0.452272,-0.711918,-12.591600,113.0,2020.0,"8,663","8,130",533,6.2
2,CO2,County,SD,Pennington County,percent,-0.746810,-0.895256,-0.721727,-1.022580,-1.682955,...,-0.995043,-0.452272,-0.711918,-12.591600,103.0,2020.0,"57,094","54,074","3,020",5.3
3,CO2,County,ME,Oxford County,percent,-0.860926,-0.447123,-0.688377,-0.949800,-1.407774,...,-0.916608,-0.367454,-0.488913,-10.451450,17.0,2020.0,"25,815","24,097","1,718",6.7
4,CO2,County,NY,Lewis County,percent,0.425832,0.918166,-0.252293,-2.176482,-6.754042,...,-4.331307,1.346825,0.921234,-10.271302,61.0,2020.0,"1,662","1,534",128,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5042,NaN,NaN,NaN,Vega Baja Municipio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,145.0,2020.0,N.A.,N.A.,N.A.,N.A.
5043,NaN,NaN,NaN,Vieques Municipio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,147.0,2020.0,N.A.,N.A.,N.A.,N.A.
5044,NaN,NaN,NaN,Villalba Municipio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,149.0,2020.0,N.A.,N.A.,N.A.,N.A.
5045,NaN,NaN,NaN,Yabucoa Municipio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,151.0,2020.0,N.A.,N.A.,N.A.,N.A.
5046,NaN,NaN,NaN,Yauco Municipio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,153.0,2020.0,N.A.,N.A.,N.A.,N.A.

In [11]:
USA.to_csv('./state_data.csv')

In [ ]:
TOTAL.to_csv('./total.csv')